import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import ThemesProvider from "./provider/ThemesProvider";


const OutfitFont = Outfit({
  subsets: ["latin"],
});
// 



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 return (
  <html lang="en" suppressHydrationWarning> 
    <body className={OutfitFont.className}>
      <ThemesProvider>
        <Navbar />
        <main className="min-h-screen">
          {children}
        </main>
        <Footer />
      </ThemesProvider>
    </body>
  </html>
);
}
